config/routes.rb
Rails.application.routes.draw do
	
	#root 'application#hello'
	root 'static_pages#home'
	
	# get  '/help',    to: 'static_pages#help'
	get  '/about',   to: 'static_pages#about'
	# get  '/contact', to: 'static_pages#contact'
	
	get  '/signup',  to: 'users#new'
	post '/signup',  to: 'users#create'
	
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	
	resources :users do
		member do
			get :following, :followers
		end
	end
	
	
	
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :microposts,          only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]
	
	resources :todos do
		collection do
			post :storefilter
		end
	end
	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :microposts, dependent: :destroy
	has_many :todos, dependent: :destroy
	has_many :active_relationships, class_name:  "Relationship",
	foreign_key: "follower_id", dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
	foreign_key: "followed_id", dependent:   :destroy
	has_many :following, through: :active_relationships,  source: :followed
	has_many :followers, through: :passive_relationships, source: :follower
	
	attr_accessor :remember_token, :activation_token, :reset_token, :login # <= OBS!!! see if login is not used
	
	before_save   :downcase_email
	before_create :create_activation_digest
	
	validates :name, presence: true, length: { maximum: 50 }
	validates :username, presence: true, length: { maximum: 50 }, uniqueness: {case_sensitive: true }
	validates_format_of :username, without: /@/i, message: "Please use an username without the '@' character!" 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
	
	validates :password, presence: true, length:{ minimum: 6 }, allow_nil: true
	has_secure_password
	
	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? 
		BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
	# Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end
	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end
	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end
	# Returns true if the given token matches the digest.
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end
	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end
	# Returns a user's status feed.
	def feed
		following_ids = "SELECT followed_id FROM relationships
		WHERE  follower_id = :user_id"
		Micropost.where("user_id IN (#{following_ids})
		OR user_id = :user_id", user_id: id)
	end
	# Follows a user.
	def follow(other_user)
		following << other_user
	end
	# Unfollows a user.
	def unfollow(other_user)
		following.delete(other_user)
	end
	# Returns true if the current user is following the other user.
	def following?(other_user)
		following.include?(other_user)
	end
	# Activates an account.
	def activate
		update_columns(activated: true, activated_at: Time.zone.now)
	end
	# Sends activation email.
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end
	# Sends activation email.
	def send_AdminNotification_email(newUserId)
		UserMailer.new_created_user_notification(self, newUserId).deliver_now
	end
	def create_reset_digest
		self.reset_token = User.new_token
		update_columns(reset_digest: User.digest(reset_token),
		reset_sent_at: Time.zone.now)
	end
	def determine_Uname_or_Uemail(username_or_email)
		if  VALID_EMAIL_REGEX.match(username_or_email)    
			user = User.find_by_email(username_or_email)
			else
			user = User.find_by_username(username_or_email)
		end
	end
	# Sends password reset email.
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end
	
	# Returns true if a password reset has expired.
	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end
	private
	
    # Converts email to all lower-case.
    def downcase_email
		email.downcase!
	end
    # Creates and assigns the activation token and digest.
    def create_activation_digest
		self.activation_token  = User.new_token
		self.activation_digest = User.digest(activation_token)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
	before_action :correct_user,   only: [:edit, :update]
	before_action :admin_or_correct_user,     only: :destroy


	def index
		numberofpages = User.paginate(page: 1).total_pages
		if(params[:page].to_i > numberofpages)
			flash[:info] = "This is the last existing users page"

			redirect_to users_path(page: numberofpages)
		else
			@users = User.paginate(page: params[:page])
		end
		store_location
	end
	def show
		@user = find(params[:id])
		@microposts = @user.microposts.paginate(page: params[:page])
		if logged_in?
			@micropost  = @user.microposts.build
			todoList = @user.todos

			@todos1 = todoList.where("status = 1")

			@lastesttodos1 = @todos1.limit(5).order("updated_at DESC")

			@todos2 = todoList.where("status = 2")
			@lastesttodos2 = @todos2.limit(5).order("updated_at DESC")

			@todos3 = todoList.where("status = 3")
			@lastesttodos3 = @todos3.limit(5).order("created_at DESC")

			@newtodo  = @user.todos.build

			# @feed_items = current_user.feed.paginate(page: params[:page])
		end
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save

			@user.send_activation_email
			@admin = User.find_by(:admin=>true)
			@admin.send_AdminNotification_email(@user.id)
			flash[:info] = "Please check your email to activate your account."
			redirect_to root_url
		else
			render 'new'
		end
	end
	def find(id)
		User.find(id)
	end
	def edit

	end
	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end
	def destroy
		find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_back_or(users_url)
	end
	def following
		@title = "Following"
		@user  = find(params[:id])
		@users = @user.following.paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@user  = find(params[:id])
		@users = @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end

	private

	def user_params
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	# Before filters

	# Confirms the correct user.
	def correct_user
		@user = find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end
	# Confirms an admin user.
	def admin_or_correct_user
		if !current_user.admin?
			@user = find(params[:id])
			if !current_user?(@user)
				redirect_to(root_url) unless current_user.admin?
			end
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
	def gravatar_for(user, options = {costomclass:"gravatar", size: 80 })
		size = options[:size]
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"

		image_tag(gravatar_url, alt: user.name, class: "#{:costomclass}")
	end
	def getTmpUsr(user)
		@tempUsr = User.find(user.id)
	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
	<div>
		<%= hidden_field_tag :followed_id, @user.id %>
	</div>
	<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if !@tempUsr.nil?%>
	<% @user = @tempUsr %>
<%end%>
<% unless current_user?(@user) %>
	<% form_id = @user.id.to_s %>
	<div id="follow_form_<%= form_id %>">
		<% if current_user.following?(@user) %>
			<%= render "unfollow" %>
		<% else %>
			<%= render "follow" %>
		<% end %>
		</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:form_url)) do |f| %>
  <%= render "shared/error_messages",  object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %>
  
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
	
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
<%= f.submit "Unfollow", class: "btn unfollow-border" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<div class="col-md-8" >
		<%= gravatar_for user, size: 50 %>
		<% getTmpUsr user %>
		<%= link_to user.name, user %>
	</div>
	<div class="col-md-2" >
	<% unless current_user?(user)%>
		<%= render "follow_form", locals: { user: @tempUsr } if logged_in? %>
		<% end %>
		</div>
		<% if current_user.admin? %>
		<div class="col-md-2" >
			| <%= link_to "Delete", user, method: :delete, data:{
				confirm:"You sure you want to delete #{user.name}?"}%>
		</div>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>
<% provide(:form_url, user_path(@user)) %>

<h1>Update your profile</h1>
<hr/>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <section>
      <div align="center">
        <%= link_to  (gravatar_for @user , costomclass:"gravatar_edit", gravatar_opt:"edit", size:100),  "http://gravatar.com/emails"  %>
        <!-- <a href="" target="_blank">Change</a> -->
      </div>
    </section>
    <section>
      <%= render "form" %>
    </section>
<hr/>
  </div>

</div>
<div class="row spacer">
  <div class="span">...</div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div align="center">
      <%= button_to "Delete Account",  @user, :class => "delete-account-btn btn btn-danger", :method => :delete,  data:{
        confirm:"You sure you want to delete #{@user.name}?"} %>
        <%# link_to "Delete", @user, method: :delete, data:{
        confirm:"You sure you want to delete #{@user.name}?"}%>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:button_text, "Create my account") %>
<% provide(:form_url, signup_path) %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="col-md-4">
		<div class="row">
			<aside class="col-md-4 user_info">
				<%= gravatar_for @user, costomclass:"gravatar", size:90 %>
			</aside>
			<div class="col-md-8 user_info">
				<div class="row name">
					<h3><%= @user.name %></h3>
				</div>
				<div align="left" class="row username">
					<% if current_user?(@user) %>
					<%= link_to edit_user_path(@user) do %>
					<i><%= @user.username %></i>
					<% end %>
					<% else %>
					<i><%= @user.username %></i>
					<% end %>
				</div>

			</div>

		</div>
		<br>
		<section class="stats">

			<%= render "shared/stats" %>
			<hr />
		</section>

		<% if current_user?(@user) %>

		<div class="micropost_form" >
			<%= render "shared/micropost_form" %>
			<hr />
		</div>

		<div class="row todo_list">
			<%= link_to todos_path  do %>
			<h3 style="text-align: center;">My To-Do List</h3>
			<% end %>

			<% if @user.todos.any? %>
			<%= render "shared/show_simple_todos" %>
			<% end %>
			<%= render "shared/todo_form" %>
		</div>
		<% end %>
	</aside>

	<div class="col-md-8">
		<%= render "follow_form", locals: { user: @user } if logged_in? %>
		<% if @user.microposts.any? %>
		<h3>Microposts (<%= @user.microposts.count %>)</h3>
		<ol class="microposts">
			<%= render @microposts %>
		</ol>
		<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>