config/routes.rb
Rails.application.routes.draw do
	
	#root 'application#hello'
	root 'static_pages#home'
	
	# get  '/help',    to: 'static_pages#help'
	get  '/about',   to: 'static_pages#about'
	# get  '/contact', to: 'static_pages#contact'
	
	get  '/signup',  to: 'users#new'
	post '/signup',  to: 'users#create'
	
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	
	resources :users do
		member do
			get :following, :followers
		end
	end
	
	
	
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :microposts,          only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]
	
	resources :todos do
		collection do
			post :storefilter
		end
	end
	
end

app/views/shared/_dialog.html.erb
<div class="modal fade" id="dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"  data-backdrop="static"  data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
	
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>

    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render "shared/error_messages", object: f.object %>
<div class="field" >
	<%= f.text_area :content, id:'content_text', maxlength: get_max_char_amount,
			placeholder: "Compose new micropost..." %>

	<div style="text-align: right;">Chars left:
		<span id="counter" data-maximum-length="<%= get_max_char_amount %>">
		 <%= get_max_char_amount %></span>
	 </div>
	
</div>
<%= f.submit "Post", class: "btn btn-primary" %>

<% end %>
<script>
$(document).ready(function() {
  var content_text = $("#content_text");
  var counter     = $("#counter");
  var max_length  = counter.data("maximum-length");

  content_text.keyup(function() {
      counter.text(max_length - $(this).val().length);
  });

});
</script>

app/views/shared/_show_simple_todos.html.erb
<!-- <h4 style="text-align: center; text-decoration: underline;">Done</h4> -->
<!-- <button type="button" class="btn btn-success">Done</button>  -->
<% if @todos1.any? %>
<table id="todos-done"  class="table table-striped table-hover" data-href="<%=%>">
	<thead>
			<caption  class="text-success" style="text-align: center;">Done</caption>
		<tr >
			<th width="70%">Title</th>
			<th width="30%">Latest update</th>
		</tr>
	</thead>
	<% @lastesttodos1.each do |todo|%>
	<%= render "shared/simple_todo", todo: todo, rowCol: "success", time: "updated"%>
	<%end%>
</table>
<p style="text-align: center;">Last <%= pluralize(@lastesttodos1.count, "completed task") %>  (out of <%= @todos1.count %>) </p>
<% else %>
<p style="text-align: center;">0 completed tasks! </br> The 5 latest updated tasks will be visible here </p>
<% end %>
<hr />

<% if @todos2.any? %>
<table id="todos-in-prog" class="table table-striped table-hover">
	<thead >
	<caption  class="text-warning" style="text-align: center;">In Progress</caption>
		<tr >
			<th width="59%">Title</th>
			<th style="text-align: center;">Latest update</th>
		</tr>
	</thead>
	<% @lastesttodos2.each do |todo|%>
	<%= render "shared/simple_todo", todo: todo, rowCol: "warning", time: "updated"%>
	<%end%>
</table>
<p style="text-align: center;">Latest <%= pluralize(@lastesttodos2.count, "updated task") %> in progress (out of <%= @todos2.count %>) </p>
<% else %>
<p style="text-align: center;">0 tasks in progress!</p>
<% end %>
<hr />
<% if @todos3.any? %>
<table id="todos-not-started" class="table table-striped table-hover">
	<thead >
	<caption class="text-danger"  style="text-align: center;">Not Started</caption>
		<tr >
			<th width="59%">Title</th>
			<th style="text-align: center;">Created at</th>
		</tr>
	</thead>
	<% @lastesttodos3.each do |todo|%>
	<%= render "shared/simple_todo", todo: todo, rowCol: "danger", time: "created"%>
	<%end%>
</table>
<p style="text-align: center;">Last <%= pluralize(@lastesttodos3.count, "created, not started task") %> (out of <%= @todos3.count %>) </p>
<% end %>

app/views/shared/_simple_todo.html.erb
<% color=rowCol||""%>

<tr id="todo-<%= todo.id %>" class="<%= color %>" >  
	<!-- clickable-row" data-href="" -->
	<!-- --------------------------OBS:------------------------------- 
	  skall vara antingen en modal (pop-up) som direkt editering 
	eller link till korrekt tab i todos! 
	 ------------------------------------------------------------- -->
<!-- 	<td ><a data-toggle="modal" data-target="#modal-window" data-remote="<%= edit_todo_path(todo) %>" class="btn btn-mini">Weigh out</a></td> -->
	<td ><%= todo.title  %></td>
	<td style="text-align: center;"><%= todo.local_time(time)%></td>
	
</tr>	

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_todo_form.html.erb
<div align="center" >
	<%= bootstrap_form_for(@newtodo, layout: :inline) do |f| %>
	<%= f.alert_message "Please fix the errors below." %>
	<div class="input-group  ">
		<%= f.text_field :title, skip_label: true, placeholder: "Compose new todo item...",  class: "form-control"  %>
		<div class="input-group-btn  "  >
			<%= button_tag "", type: "submit", class: "btn btn-primary glyphicon glyphicon-plus"  %>
		</div>
	</div>
	<% end %>
</div>

app/views/shared/_user_info.html.erb
<div class="row user_info">
  <aside class="col-md-4 ">
    <%= link_to gravatar_for(current_user, size: 90), current_user %>
  </aside>
  <div class="col-md-8">
    <div class="row name">
      <%= link_to user_path(current_user) do %>
      <h3><%= current_user.name %></h3>
      <% end %>
    </div>
    <div align="left" class="row username">
      <i><%= current_user.username %></i>
      <br>
      <span><%= pluralize(current_user.microposts.count, "micropost") %></span>
    </div>

  </div>

</div>
<br>